### ISSUE TITLE
Missing semicolon in produced output

### ISSUE THREAD

**Issue by besi** [jbrownssf/ionic-environment-flags#2]
Hy there I've been using your solution and it's working great. Thanks a lot for spending time to build this.

Just a minor issue:
The generated provider does not have semicolons:

![screen shot 2017-04-03 at 15 49 39](https://cloud.githubusercontent.com/assets/160412/24613716/6de2b10a-1889-11e7-91f2-fe966f922df7.png)

Also the IDE tells me that the constant is not required.

**Comment by jpbrown250** [comment]
thank you for this feed back, I am glad it is working out for you. I will fix it right now.
